name: onedrive_upload
on:
  watch:
    types: [started]
    
env: 
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       - uses: shaowenchen/debugger-action@v2
         name: debugger
         timeout-minutes: 900
         continue-on-error: true
         with:
           ngrok_token: ${{ secrets.NGROK_TOKEN }}
